"use client"

import * as React from "react"

type Language = "pt-BR" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  "pt-BR": {
    // Navigation
    "nav.platform": "Plataforma",
    "nav.ai": "CastorMind-IA",
    "nav.segments": "Segmentos",
    "nav.pricing": "Planos",
    "nav.login": "Entrar",
    "nav.demo": "Agendar Demo",
    "nav.theme": "Tema",
    "nav.language": "Idioma",
    
    // Hero
    "hero.badge": "Potencializado por CastorMind-IA",
    "hero.title": "Gestão de obras com",
    "hero.titleHighlight": "Inteligência Artificial",
    "hero.subtitle": "Planeje, execute e controle cada etapa da sua obra com uma plataforma que integra orçamentos SINAPI, cronogramas preditivos e controle financeiro em um unico ambiente.",
    "hero.cta": "Entrar na Lista de Espera",
    "hero.ctaSecondary": "Assistir Demonstração",
    "hero.stat1": "Integração nativa com tabela SINAPI",
    "hero.stat2": "Cronogramas preditivos com machine learning",
    "hero.stat3": "Portal de acompanhamento para clientes",
    "hero.aiReady": "Inteligência Artificial Aplicada",
    "hero.trusted": "Projetado para construtoras, escritórios de arquitetura e engenharia civil no Brasil",
    
    // Features
    "features.badge": "Plataforma Integrada",
    "features.title": "Todas as ferramentas que a sua operação exige",
    "features.subtitle": "Do levantamento de custos à entrega da chave, cada processo centralizado e otimizado pela CastorMind-IA",
    "features.budget.title": "Orçamentos Assistidos por IA",
    "features.budget.desc": "Elabore orçamentos detalhados em minutos com base na tabela SINAPI e no histórico de obras similares, utilizando modelos de aprendizado de máquina",
    "features.schedule.title": "Cronograma Preditivo",
    "features.schedule.desc": "Defina marcos, acompanhe dependências e receba alertas antecipados de risco de atraso com base em análise de dados",
    "features.financial.title": "Controle Financeiro Completo",
    "features.financial.desc": "Gerencie fluxo de caixa, medições, notas fiscais e conciliação bancária em um painel unificado",
    "features.diary.title": "Diário de Obra Digital",
    "features.diary.desc": "Registre ocorrências, condições climáticas, fotos geolocalizadas e colete assinaturas digitais em campo",
    "features.portal.title": "Portal do Cliente",
    "features.portal.desc": "Ofereça ao seu cliente acesso em tempo real ao progresso da obra, fotos, documentos e extrato financeiro",
    "features.procurement.title": "Gestão de Suprimentos",
    "features.procurement.desc": "Centralize cotações, emita pedidos de compra e controle entregas com rastreamento de fornecedores",
    "features.mobile.title": "Aplicativo Mobile",
    "features.mobile.desc": "Acesse a plataforma completa pelo celular ou tablet, inclusive em modo offline no canteiro de obras",
    "features.reports.title": "Relatórios e Indicadores",
    "features.reports.desc": "Dashboards personalizáveis com KPIs de performance, desvio orçamentário e produtividade por etapa",
    
    // AI Section
    "ai.badge": "CastorMind-IA",
    "ai.title": "Inteligência Artificial projetada para a construção civil",
    "ai.subtitle": "A CastorMind-IA foi desenvolvida com dados estruturados do setor de construção brasileiro, incluindo bases SINAPI e normas ABNT, para oferecer automação e análise com relevância real para a sua operação.",
    "ai.feature1.title": "Estimativa Inteligente de Custos",
    "ai.feature1.desc": "Modelos preditivos que cruzam dados SINAPI, composições de custo e variáveis regionais para gerar estimativas fundamentadas",
    "ai.feature2.title": "Análise Preditiva de Cronograma",
    "ai.feature2.desc": "Identificação antecipada de riscos de atraso com base em padrões de obras similares e variáveis sazonais",
    "ai.feature3.title": "Otimização de Compras",
    "ai.feature3.desc": "Recomendações de fornecedores e janelas de compra ideais com base em histórico de preços e volume",
    "ai.feature4.title": "Monitoramento de Rentabilidade",
    "ai.feature4.desc": "Acompanhamento contínuo de margens e alertas automáticos sobre desvios orçamentários significativos",
    "ai.cta": "Explorar CastorMind-IA",
    "ai.capability1": "Base SINAPI",
    "ai.capability2": "Normas ABNT",
    "ai.capability3": "Análise Contínua",
    
    // Segments
    "segments.badge": "Segmentos Atendidos",
    "segments.title": "Soluções para cada perfil de operação",
    "segments.subtitle": "Funcionalidades específicas para atender as demandas de cada profissional da cadeia construtiva",
    "segments.builders.title": "Construtoras",
    "segments.builders.desc": "Controle de múltiplas obras em paralelo, com gestão integrada de custos, prazos e equipes",
    "segments.architects.title": "Escritórios de Arquitetura",
    "segments.architects.desc": "Do projeto executivo ao acompanhamento de obra, com rastreamento completo de especificações",
    "segments.engineers.title": "Engenheiros Civis",
    "segments.engineers.desc": "Controle técnico e financeiro com relatórios detalhados, diário de obra e gestão documental",
    "segments.managers.title": "Gestores e Mestres de Obra",
    "segments.managers.desc": "Ferramentas de campo com modo offline, registro fotográfico e comunicação em tempo real",
    "segments.admin.title": "Administrativo",
    "segments.admin.desc": "Gestão centralizada de contratos, fluxo financeiro, documentação fiscal e compliance",
    "segments.clients.title": "Portal do Proprietário",
    "segments.clients.desc": "Interface dedicada para o cliente final acompanhar cada evolução da sua obra com transparência",
    
    // Testimonials / Why Section
    "testimonials.badge": "Diferenciais",
    "testimonials.title": "Por que escolher a CastorWorks",
    "testimonials.subtitle": "Conheça os fundamentos técnicos e operacionais que fazem da CastorWorks a escolha certa para a sua operação",
    "testimonials.featured.badge": "Desenvolvido para o Brasil",
    "testimonials.featured.title": "Tecnologia alinhada à realidade da construção civil brasileira",
    "testimonials.featured.desc": "Construída sobre a tabela SINAPI e em conformidade com as normas ABNT, a CastorWorks foi projetada para atender às particularidades do mercado brasileiro de ponta a ponta.",
    "testimonials.featured.cta": "Entrar na Lista de Espera",
    "testimonials.reason1.title": "Orçamentos Fundamentados, Não Estimativas",
    "testimonials.reason1.desc": "Enquanto métodos convencionais dependem de planilhas manuais e referências desatualizadas, a CastorMind-IA cruza dados SINAPI atualizados com o perfil da obra para gerar orçamentos consistentes.",
    "testimonials.reason2.title": "Prevenção, Não Correção",
    "testimonials.reason2.desc": "A análise preditiva identifica padrões de risco antes que se materializem em atrasos ou estouros orçamentários, permitindo ação preventiva pela gestão.",
    "testimonials.reason3.title": "Transparência Integral com o Cliente",
    "testimonials.reason3.desc": "O portal do proprietário oferece acesso em tempo real ao andamento da obra, eliminando ruídos de comunicação e fortalecendo a relação de confiança.",
    "testimonials.reason4.title": "Operação Conectada em Campo",
    "testimonials.reason4.desc": "O aplicativo mobile com modo offline permite que engenheiros de campo e mestres de obra registrem informações diretamente do canteiro, sem interrupções.",
    
    // CTA
    "cta.title": "Leve inteligência artificial para a sua gestão de obras",
    "cta.subtitle": "Solicite acesso antecipado e descubra como a CastorMind-IA pode transformar a operação da sua construtora ou escritório",
    "cta.button": "Entrar na Lista de Espera",
    "cta.buttonSecondary": "Falar com um Consultor",
    "cta.note": "Período de avaliação gratuito. Sem necessidade de cartão de crédito.",
    "cta.benefit1": "Sem compromisso financeiro",
    "cta.benefit2": "Configuração assistida em minutos",
    "cta.benefit3": "Suporte técnico especializado",
    "cta.highlight1.title": "Acesso Antecipado",
    "cta.highlight1.desc": "Seja um dos primeiros a operar com a plataforma completa",
    "cta.highlight2.title": "Dados Protegidos",
    "cta.highlight2.desc": "Infraestrutura com criptografia de ponta a ponta e conformidade LGPD",
    "cta.highlight3.title": "Implantação Assistida",
    "cta.highlight3.desc": "Equipe técnica dedicada para acompanhar toda a configuração inicial",

    // Waitlist
    "waitlist.badge": "Acesso antecipado",
    "waitlist.title": "Entre na lista de espera da CastorWorks",
    "waitlist.subtitle": "Garanta prioridade no lançamento, onboarding guiado e atualizações exclusivas da plataforma.",
    "waitlist.trust": "Sem spam. Usaremos seus dados apenas para contato sobre a CastorWorks.",
    "waitlist.form.fullName": "Nome completo",
    "waitlist.form.fullNamePlaceholder": "Como devemos chamar você?",
    "waitlist.form.companyName": "Nome da empresa",
    "waitlist.form.companyNamePlaceholder": "Construtora, escritório ou incorporadora",
    "waitlist.form.email": "Email corporativo",
    "waitlist.form.emailPlaceholder": "voce@empresa.com",
    "waitlist.form.cellPhone": "Celular",
    "waitlist.form.cellPhonePlaceholder": "(11) 99999-9999",
    "waitlist.form.moreInfoRequest": "O que você quer saber primeiro?",
    "waitlist.form.moreInfoRequestPlaceholder": "Conte rapidamente como a CastorWorks pode ajudar sua operação.",
    "waitlist.form.submit": "Entrar na lista",
    "waitlist.form.submitting": "Adicionando você...",
    "waitlist.form.successTitle": "Você está na lista",
    "waitlist.form.successDescription": "Seu interesse foi registrado e acabamos de enviar um email de confirmação.",
    "waitlist.form.successCta": "Fechar",
    "waitlist.form.error": "Não foi possível concluir seu cadastro agora. Tente novamente em alguns instantes.",
    "waitlist.form.duplicate": "Você já está na lista. Vamos manter você informado por email.",
    "waitlist.toast.success": "Seu nome foi adicionado à lista de espera.",
    "waitlist.toast.duplicate": "Seu email já está cadastrado na lista de espera.",
    "waitlist.toast.error": "Não foi possível adicionar seu nome à lista de espera.",
    "waitlist.validation.fullName": "Informe seu nome completo.",
    "waitlist.validation.companyName": "Informe o nome da sua empresa.",
    "waitlist.validation.email": "Informe um email válido.",
    "waitlist.validation.cellPhone": "Informe um celular válido.",
    "waitlist.card.priority": "Prioridade no lançamento",
    "waitlist.card.priorityDesc": "Receba convite antes da abertura pública.",
    "waitlist.card.guided": "Onboarding consultivo",
    "waitlist.card.guidedDesc": "Vamos entender seu fluxo e orientar os primeiros passos.",
    "waitlist.card.updates": "Atualizações exclusivas",
    "waitlist.card.updatesDesc": "Fique por dentro das novidades de produto e IA aplicada à construção.",
    
    // Pricing
    "pricing.badge": "Planos e Preços",
    "pricing.title": "O plano certo para a sua operação",
    "pricing.subtitle": "Escolha o nível de funcionalidade adequado ao porte e à complexidade dos seus projetos",
    "pricing.monthly": "/mês",
    "pricing.cta.free": "Começar Grátis",
    "pricing.cta.starter": "Iniciar Período de Avaliação",
    "pricing.cta.architects": "Iniciar Período de Avaliação",
    "pricing.cta.construction": "Falar com Consultor",
    "pricing.popular": "Mais Escolhido",
    "pricing.custom": "Sob Consulta",
    "pricing.free.name": "Gratuito",
    "pricing.free.desc": "Para profissionais autônomos que desejam conhecer a plataforma",
    "pricing.free.price": "R$ 0",
    "pricing.free.f1": "1 projeto ativo",
    "pricing.free.f2": "Orçamento básico com SINAPI",
    "pricing.free.f3": "Diário de obra digital",
    "pricing.free.f4": "Aplicativo mobile",
    "pricing.free.f5": "Suporte por e-mail",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "Para pequenas construtoras e profissionais em crescimento",
    "pricing.starter.price": "R$ 197",
    "pricing.starter.f1": "Até 5 projetos ativos",
    "pricing.starter.f2": "Orçamentos com CastorMind-IA",
    "pricing.starter.f3": "Cronograma inteligente",
    "pricing.starter.f4": "Controle financeiro básico",
    "pricing.starter.f5": "Portal do cliente",
    "pricing.starter.f6": "Relatórios padrão",
    "pricing.starter.f7": "Suporte prioritário",
    "pricing.architects.name": "Arquitetura",
    "pricing.architects.desc": "Para escritórios de arquitetura e engenharia com demandas avançadas",
    "pricing.architects.price": "R$ 397",
    "pricing.architects.f1": "Até 20 projetos ativos",
    "pricing.architects.f2": "Tudo do plano Starter",
    "pricing.architects.f3": "Gestão de suprimentos",
    "pricing.architects.f4": "Análise preditiva de cronograma",
    "pricing.architects.f5": "Relatórios personalizáveis",
    "pricing.architects.f6": "Múltiplos usuários por projeto",
    "pricing.architects.f7": "Integrações via API",
    "pricing.architects.f8": "Suporte por chat e telefone",
    "pricing.construction.name": "Obras",
    "pricing.construction.desc": "Para construtoras e incorporadoras com operações complexas e alto volume",
    "pricing.construction.price": "",
    "pricing.construction.f1": "Projetos ilimitados",
    "pricing.construction.f2": "Tudo do plano Arquitetura",
    "pricing.construction.f3": "CastorMind-IA avançada",
    "pricing.construction.f4": "Monitoramento de rentabilidade",
    "pricing.construction.f5": "Gestão multi-empresa",
    "pricing.construction.f6": "SLA de suporte dedicado",
    "pricing.construction.f7": "Implantação assistida",
    "pricing.construction.f8": "Treinamento personalizado",
    "pricing.construction.f9": "Consultor de sucesso dedicado",
    
    // Footer
    "footer.description": "Plataforma de gestão de obras potencializada por inteligência artificial. Projetada para o mercado brasileiro de construção civil.",
    "footer.platform": "Plataforma",
    "footer.resources": "Recursos",
    "footer.company": "Empresa",
    "footer.legal": "Legal",
    "footer.rights": "Todos os direitos reservados.",
  },
  "en": {
    // Navigation
    "nav.platform": "Platform",
    "nav.ai": "CastorMind-AI",
    "nav.segments": "Segments",
    "nav.pricing": "Pricing",
    "nav.login": "Sign In",
    "nav.demo": "Book a Demo",
    "nav.theme": "Theme",
    "nav.language": "Language",
    
    // Hero
    "hero.badge": "Powered by CastorMind-AI",
    "hero.title": "Construction management with",
    "hero.titleHighlight": "Artificial Intelligence",
    "hero.subtitle": "Plan, execute, and control every phase of your project with a platform that integrates SINAPI-based budgets, predictive scheduling, and financial management in a single environment.",
    "hero.cta": "Join the Waitlist",
    "hero.ctaSecondary": "Watch Demo",
    "hero.stat1": "Native integration with SINAPI cost database",
    "hero.stat2": "Predictive scheduling with machine learning",
    "hero.stat3": "Client progress tracking portal",
    "hero.aiReady": "Applied Artificial Intelligence",
    "hero.trusted": "Designed for construction firms, architecture offices, and civil engineering in Brazil",
    
    // Features
    "features.badge": "Integrated Platform",
    "features.title": "Every tool your operation demands",
    "features.subtitle": "From cost estimation to key handover, every process centralized and optimized by CastorMind-AI",
    "features.budget.title": "AI-Assisted Budgets",
    "features.budget.desc": "Build detailed budgets in minutes using SINAPI cost tables and historical project data through machine learning models",
    "features.schedule.title": "Predictive Scheduling",
    "features.schedule.desc": "Define milestones, track dependencies, and receive early delay risk alerts based on data analysis",
    "features.financial.title": "Complete Financial Control",
    "features.financial.desc": "Manage cash flow, measurements, invoices, and bank reconciliation in a unified dashboard",
    "features.diary.title": "Digital Site Diary",
    "features.diary.desc": "Record events, weather conditions, geotagged photos, and collect digital signatures in the field",
    "features.portal.title": "Client Portal",
    "features.portal.desc": "Give your clients real-time access to construction progress, photos, documents, and financial statements",
    "features.procurement.title": "Supply Management",
    "features.procurement.desc": "Centralize quotations, issue purchase orders, and track deliveries with supplier management",
    "features.mobile.title": "Mobile Application",
    "features.mobile.desc": "Access the full platform from your phone or tablet, including offline mode on the construction site",
    "features.reports.title": "Reports and KPIs",
    "features.reports.desc": "Customizable dashboards with performance KPIs, budget variance, and productivity metrics by phase",
    
    // AI Section
    "ai.badge": "CastorMind-AI",
    "ai.title": "Artificial Intelligence engineered for construction",
    "ai.subtitle": "CastorMind-AI was developed using structured data from Brazil's construction sector, including SINAPI databases and ABNT standards, to deliver automation and analysis with real operational relevance.",
    "ai.feature1.title": "Intelligent Cost Estimation",
    "ai.feature1.desc": "Predictive models that cross-reference SINAPI data, cost compositions, and regional variables to generate grounded estimates",
    "ai.feature2.title": "Predictive Schedule Analysis",
    "ai.feature2.desc": "Early identification of delay risks based on patterns from similar projects and seasonal variables",
    "ai.feature3.title": "Procurement Optimization",
    "ai.feature3.desc": "Supplier recommendations and ideal purchase windows based on pricing history and volume data",
    "ai.feature4.title": "Profitability Monitoring",
    "ai.feature4.desc": "Continuous margin tracking and automatic alerts on significant budget deviations",
    "ai.cta": "Explore CastorMind-AI",
    "ai.capability1": "SINAPI Database",
    "ai.capability2": "ABNT Standards",
    "ai.capability3": "Continuous Analysis",
    
    // Segments
    "segments.badge": "Segments Served",
    "segments.title": "Solutions for every operational profile",
    "segments.subtitle": "Purpose-built functionality to meet the demands of every professional in the construction chain",
    "segments.builders.title": "Construction Firms",
    "segments.builders.desc": "Manage multiple projects in parallel with integrated cost, deadline, and team oversight",
    "segments.architects.title": "Architecture Offices",
    "segments.architects.desc": "From executive design to site monitoring, with full specification tracking",
    "segments.engineers.title": "Civil Engineers",
    "segments.engineers.desc": "Technical and financial control with detailed reports, site diary, and document management",
    "segments.managers.title": "Site Managers and Supervisors",
    "segments.managers.desc": "Field tools with offline mode, photo documentation, and real-time communication",
    "segments.admin.title": "Administration",
    "segments.admin.desc": "Centralized contract management, financial workflow, tax documentation, and compliance",
    "segments.clients.title": "Owner Portal",
    "segments.clients.desc": "A dedicated interface for the end client to track every development of their project with transparency",
    
    // Testimonials / Why Section
    "testimonials.badge": "Differentiators",
    "testimonials.title": "Why choose CastorWorks",
    "testimonials.subtitle": "Discover the technical and operational foundations that make CastorWorks the right choice for your operation",
    "testimonials.featured.badge": "Built for Brazil",
    "testimonials.featured.title": "Technology aligned with Brazilian construction realities",
    "testimonials.featured.desc": "Built on the SINAPI cost table and in compliance with ABNT standards, CastorWorks is engineered to address the specific requirements of the Brazilian construction market.",
    "testimonials.featured.cta": "Join the Waitlist",
    "testimonials.reason1.title": "Grounded Budgets, Not Guesswork",
    "testimonials.reason1.desc": "While conventional methods rely on manual spreadsheets and outdated references, CastorMind-AI cross-references current SINAPI data with project parameters to produce consistent budgets.",
    "testimonials.reason2.title": "Prevention, Not Correction",
    "testimonials.reason2.desc": "Predictive analysis identifies risk patterns before they materialize into delays or budget overruns, enabling proactive management decisions.",
    "testimonials.reason3.title": "Complete Client Transparency",
    "testimonials.reason3.desc": "The owner portal provides real-time access to project progress, eliminating communication gaps and strengthening the trust relationship.",
    "testimonials.reason4.title": "Connected Field Operations",
    "testimonials.reason4.desc": "The mobile application with offline capability allows field engineers and site supervisors to record information directly from the construction site without interruption.",
    
    // CTA
    "cta.title": "Bring artificial intelligence to your construction management",
    "cta.subtitle": "Request early access and discover how CastorMind-AI can transform the operation of your construction firm or office",
    "cta.button": "Join the Waitlist",
    "cta.buttonSecondary": "Speak with a Consultant",
    "cta.note": "Free evaluation period. No credit card required.",
    "cta.benefit1": "No financial commitment",
    "cta.benefit2": "Assisted setup in minutes",
    "cta.benefit3": "Specialized technical support",
    "cta.highlight1.title": "Early Access",
    "cta.highlight1.desc": "Be among the first to operate with the full platform",
    "cta.highlight2.title": "Protected Data",
    "cta.highlight2.desc": "Infrastructure with end-to-end encryption and LGPD compliance",
    "cta.highlight3.title": "Guided Implementation",
    "cta.highlight3.desc": "Dedicated technical team to guide your entire initial setup",

    // Waitlist
    "waitlist.badge": "Early access",
    "waitlist.title": "Join the CastorWorks waiting list",
    "waitlist.subtitle": "Secure launch priority, guided onboarding, and exclusive updates from the platform.",
    "waitlist.trust": "No spam. We will only use your details to contact you about CastorWorks.",
    "waitlist.form.fullName": "Full name",
    "waitlist.form.fullNamePlaceholder": "What should we call you?",
    "waitlist.form.companyName": "Company name",
    "waitlist.form.companyNamePlaceholder": "Construction firm, office, or developer",
    "waitlist.form.email": "Work email",
    "waitlist.form.emailPlaceholder": "you@company.com",
    "waitlist.form.cellPhone": "Mobile phone",
    "waitlist.form.cellPhonePlaceholder": "+1 (555) 123-4567",
    "waitlist.form.moreInfoRequest": "What do you want to learn first?",
    "waitlist.form.moreInfoRequestPlaceholder": "Tell us briefly how CastorWorks could help your operation.",
    "waitlist.form.submit": "Join the list",
    "waitlist.form.submitting": "Adding you...",
    "waitlist.form.successTitle": "You are on the list",
    "waitlist.form.successDescription": "Your interest was recorded and we just sent you a confirmation email.",
    "waitlist.form.successCta": "Close",
    "waitlist.form.error": "We could not complete your signup right now. Please try again in a moment.",
    "waitlist.form.duplicate": "You are already on the list. We will keep you posted by email.",
    "waitlist.toast.success": "Your name was added to the waiting list.",
    "waitlist.toast.duplicate": "Your email is already on the waiting list.",
    "waitlist.toast.error": "We could not add your name to the waiting list.",
    "waitlist.validation.fullName": "Enter your full name.",
    "waitlist.validation.companyName": "Enter your company name.",
    "waitlist.validation.email": "Enter a valid email address.",
    "waitlist.validation.cellPhone": "Enter a valid mobile phone number.",
    "waitlist.card.priority": "Launch priority",
    "waitlist.card.priorityDesc": "Get invited before public rollout.",
    "waitlist.card.guided": "Guided onboarding",
    "waitlist.card.guidedDesc": "We will learn your workflow and help you start strong.",
    "waitlist.card.updates": "Exclusive updates",
    "waitlist.card.updatesDesc": "Stay close to product releases and AI features for construction.",
    
    // Pricing
    "pricing.badge": "Plans and Pricing",
    "pricing.title": "The right plan for your operation",
    "pricing.subtitle": "Choose the level of functionality suited to the size and complexity of your projects",
    "pricing.monthly": "/month",
    "pricing.cta.free": "Start Free",
    "pricing.cta.starter": "Start Free Trial",
    "pricing.cta.architects": "Start Free Trial",
    "pricing.cta.construction": "Talk to a Consultant",
    "pricing.popular": "Most Popular",
    "pricing.custom": "Custom",
    "pricing.free.name": "Free",
    "pricing.free.desc": "For independent professionals exploring the platform",
    "pricing.free.price": "R$ 0",
    "pricing.free.f1": "1 active project",
    "pricing.free.f2": "Basic SINAPI budgeting",
    "pricing.free.f3": "Digital site diary",
    "pricing.free.f4": "Mobile application",
    "pricing.free.f5": "Email support",
    "pricing.starter.name": "Starter",
    "pricing.starter.desc": "For small firms and growing professionals",
    "pricing.starter.price": "R$ 197",
    "pricing.starter.f1": "Up to 5 active projects",
    "pricing.starter.f2": "CastorMind-AI budgets",
    "pricing.starter.f3": "Smart scheduling",
    "pricing.starter.f4": "Basic financial control",
    "pricing.starter.f5": "Client portal",
    "pricing.starter.f6": "Standard reports",
    "pricing.starter.f7": "Priority support",
    "pricing.architects.name": "Architects",
    "pricing.architects.desc": "For architecture and engineering offices with advanced requirements",
    "pricing.architects.price": "R$ 397",
    "pricing.architects.f1": "Up to 20 active projects",
    "pricing.architects.f2": "Everything in Starter",
    "pricing.architects.f3": "Supply management",
    "pricing.architects.f4": "Predictive schedule analysis",
    "pricing.architects.f5": "Customizable reports",
    "pricing.architects.f6": "Multiple users per project",
    "pricing.architects.f7": "API integrations",
    "pricing.architects.f8": "Chat and phone support",
    "pricing.construction.name": "Construction",
    "pricing.construction.desc": "For construction firms and developers with complex, high-volume operations",
    "pricing.construction.price": "",
    "pricing.construction.f1": "Unlimited projects",
    "pricing.construction.f2": "Everything in Architects",
    "pricing.construction.f3": "Advanced CastorMind-AI",
    "pricing.construction.f4": "Profitability monitoring",
    "pricing.construction.f5": "Multi-company management",
    "pricing.construction.f6": "Dedicated support SLA",
    "pricing.construction.f7": "Guided implementation",
    "pricing.construction.f8": "Custom training",
    "pricing.construction.f9": "Dedicated success consultant",
    
    // Footer
    "footer.description": "Construction management platform powered by artificial intelligence. Designed for the Brazilian construction market.",
    "footer.platform": "Platform",
    "footer.resources": "Resources",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.rights": "All rights reserved.",
  }
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>("pt-BR")

  React.useEffect(() => {
    const stored = localStorage.getItem("castorworks-language") as Language
    if (stored && (stored === "pt-BR" || stored === "en")) {
      setLanguageState(stored)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("castorworks-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = React.useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
