// Suppress GoTrueClient debug logs by overriding console methods BEFORE any imports
if (typeof window !== 'undefined') {
  // Store original methods immediately
  const originalMethods = {
    log: console.log,
    debug: console.debug,
    info: console.info,
    warn: console.warn,
    error: console.error
  };

  // More aggressive console override that checks all arguments
  const createSuppressedMethod = (originalMethod: (...args: any[]) => void) => {
    return function(this: Console, ...args: any[]) {
      // Check all arguments for GoTrueClient patterns
      for (const arg of args) {
        if (typeof arg === 'string') {
          if (arg.includes('GoTrueClient@') ||
              arg.includes('#_acquireLock') ||
              arg.includes('#_useSession') ||
              arg.includes('#__loadSession') ||
              arg.includes('#getSession') ||
              arg.includes('GoTrueClient.ts:') ||
              arg.includes('GoTrueClient ')) {
            return; // Suppress the log
          }
        }
      }
      // Call original method for non-GoTrueClient logs
      return originalMethod.apply(this, args);
    };
  };

  // Apply overrides immediately
  console.log = createSuppressedMethod(originalMethods.log);
  console.debug = createSuppressedMethod(originalMethods.debug);
  console.info = createSuppressedMethod(originalMethods.info);
  console.warn = createSuppressedMethod(originalMethods.warn);
  console.error = createSuppressedMethod(originalMethods.error);

  // Also override console methods on window object if available
  if (window.console) {
    window.console.log = console.log;
    window.console.debug = console.debug;
    window.console.info = console.info;
    window.console.warn = console.warn;
    window.console.error = console.error;
  }
}

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_URL = (() => {
  if (!rawSupabaseUrl) return rawSupabaseUrl;

  if (typeof window === "undefined") {
    return rawSupabaseUrl;
  }

  try {
    const url = new URL(rawSupabaseUrl);
    if (window.location.protocol === "https:") {
      url.protocol = "https:";
    }
    if (url.hostname === "dev.castorworks.cloud" || url.hostname === "castorworks.cloud") {
      url.port = "";
    }
    // Ensure we don't have a trailing slash which can cause double slashes in API calls
    return url.toString().replace(/\/$/, "");
  } catch {
    return rawSupabaseUrl?.replace(/\/$/, "");
  }
})();
const publishableKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Enhanced logging for authentication debugging - necessary for troubleshooting sign-in issues
const createSupabaseClient = () => {
  /*
  console.log('🔧 [Supabase] Initializing client with config:', {
    url: SUPABASE_URL,
    hasKey: !!publishableKey,
    environment: import.meta.env.MODE
  });
  */

  if (!SUPABASE_URL) {
    console.error('🚫 [Supabase] CRITICAL: VITE_SUPABASE_URL is not set');
    throw new Error('Missing VITE_SUPABASE_URL environment variable');
  }

  if (!publishableKey) {
    console.error('🚫 [Supabase] CRITICAL: VITE_SUPABASE_ANON_KEY/VITE_SUPABASE_PUBLISHABLE_KEY is not set');
    throw new Error('Missing Supabase publishable key environment variable');
  }

  // console.log('✅ [Supabase] Client configuration validated');

  const shouldLogStorageWarnings = import.meta.env.MODE !== 'test';

  // Detect if we're in private mode - comprehensive check
  const isPrivateMode = (() => {
    // Check localStorage
    let localStorageBlocked = false;
    try {
      const testKey = '__private_mode_test__';
      if (typeof globalThis.localStorage !== 'undefined') {
        globalThis.localStorage.setItem(testKey, 'test');
        globalThis.localStorage.removeItem(testKey);
      } else {
        localStorageBlocked = true;
      }
    } catch (e) {
      // console.warn('🔒 [Supabase] localStorage blocked - private mode detected');
      localStorageBlocked = true;
    }

    // Check sessionStorage
    let sessionStorageBlocked = false;
    try {
      const testKey = '__session_test__';
      if (typeof globalThis.sessionStorage !== 'undefined') {
        globalThis.sessionStorage.setItem(testKey, 'test');
        globalThis.sessionStorage.removeItem(testKey);
      } else {
        sessionStorageBlocked = true;
      }
    } catch (e) {
      // console.warn('🔒 [Supabase] sessionStorage also blocked - severe private mode restrictions');
      sessionStorageBlocked = true;
    }

    const privateMode = localStorageBlocked;
    /*
    console.log('🔒 [Supabase] Storage availability check:', {
      localStorage: !localStorageBlocked,
      sessionStorage: !sessionStorageBlocked,
      privateMode,
      willUseSessionStorage: privateMode && !sessionStorageBlocked
    });
    */

    return privateMode;
  })();

  // Configure auth based on storage availability
  const authConfig = (() => {
    if (isPrivateMode) {
      // In private mode, try sessionStorage, but if that's also blocked, we can't authenticate
      try {
        const testKey = '__auth_test__';
        if (typeof globalThis.sessionStorage === 'undefined') throw new Error('sessionStorage undefined');
        globalThis.sessionStorage.setItem(testKey, 'test');
        globalThis.sessionStorage.removeItem(testKey);
        // console.log('✅ [Supabase] Using sessionStorage for auth in private mode');
        return {
          storage: globalThis.sessionStorage,
          persistSession: false, // Sessions won't persist anyway
          autoRefreshToken: false, // Disable auto-refresh in private mode
        };
      } catch (e) {
        // console.error('🚫 [Supabase] CRITICAL: Both localStorage and sessionStorage blocked in private mode');
        // console.error('🚫 [Supabase] Authentication will not work in this browser environment');
        // Fall back to localStorage anyway - it will fail gracefully
        return {
          storage: typeof globalThis.localStorage !== 'undefined' ? globalThis.localStorage : undefined,
          persistSession: false,
          autoRefreshToken: false,
        };
      }
    } else {
      // Normal mode - use localStorage
      // console.log('✅ [Supabase] Using localStorage for auth in normal mode');
      return {
        storage: typeof globalThis.localStorage !== 'undefined' ? globalThis.localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      };
    }
  })();

  return createClient<any>(SUPABASE_URL, publishableKey, {
    auth: {
      ...authConfig,
      debug: false, // Disable debug logging to prevent console noise during login
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    global: {
      headers: {
        'X-Client-Info': `castorworks-web${isPrivateMode ? '-private-mode' : ''}`
      }
    }
  });
};

export const supabase: any = createSupabaseClient();



// Add request/response logging in development - necessary for debugging API failures
if (import.meta.env.DEV) {
  // console.log('🔧 [Supabase] Development mode: Request logging enabled');

  // Log all outgoing requests - critical for debugging authentication API calls
  const originalFetch = globalThis.fetch;
  globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    const url = input instanceof Request ? input.url : input instanceof URL ? input.href : input;
    const isSupabaseRequest = typeof url === 'string' && (
      url.includes('supabase') || 
      (SUPABASE_URL && url.includes(new URL(SUPABASE_URL).hostname))
    );
    
    if (isSupabaseRequest) {
      /*
      console.log('📤 [Supabase] API Request:', {
        url: url.replace(/\/rest\/v1\//, '/rest/v1/[REDACTED]/'),
        method: input instanceof Request ? input.method : init?.method || 'GET',
        timestamp: new Date().toISOString()
      });
      */
    }
    return originalFetch(input, init);
  };
}
