/**
 * Financial Risk Alerts Engine
 * 
 * Scans cashflow snapshots for High/Critical risks and triggers
 * automated Email notifications to stakeholders.
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL') ?? ''
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    const requestBody = await req.json().catch(() => ({}))
    const filterProjectId = requestBody.project_id

    console.log(`[Risk Alerts] Starting scan... ${filterProjectId ? `Filtering for project: ${filterProjectId}` : 'All projects'}`)

    // 1. Fetch unalerted Critical/High risk snapshots
    let query = supabase
      .from('financial_cashflow_snapshots')
      .select('*, projects(name)')
      .in('risk_level', ['critical', 'high'])
      .eq('is_alerted', false)

    if (filterProjectId) {
      query = query.eq('project_id', filterProjectId)
    }

    const { data: snapshots, error: snapError } = await query.order('week_start_date', { ascending: true })

    if (snapError) throw snapError
    if (!snapshots || snapshots.length === 0) {
      return new Response(JSON.stringify({ success: true, message: 'No new risks detected' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // 2. Fetch admin email for alerts
    const { data: company } = await supabase.from('company_settings').select('*').single()
    const adminEmail = company?.email || 'alex.macedo.ca@gmail.com'

    // 3. Group by Project
    const projectRisks = new Map()
    for (const snap of snapshots) {
      if (!projectRisks.has(snap.project_id)) {
        projectRisks.set(snap.project_id, {
          projectName: snap.projects?.name || 'Unknown Project',
          risks: []
        })
      }
      projectRisks.get(snap.project_id).risks.push(snap)
    }

    const alertedIds: string[] = []

    for (const [_projectId, info] of projectRisks.entries()) {
      const highestRisk = info.risks.find((r: any) => r.risk_level === 'critical') ? 'CRITICAL' : 'HIGH'
      
      const message = `🚨 *Financial Risk Alert: ${info.projectName}*\n\n` +
        `CastorMind AI has detected ${highestRisk} liquidity risks in your 13-week forecast.\n\n` +
        `*Details:*\n` +
        `• Next Risk Window: ${info.risks[0].week_start_date}\n` +
        `• Projected Min Balance: ${info.risks[0].projected_balance} BRL\n\n` +
        `⚠️ *Action Required:* Please review the Cashflow Dashboard.\n\n` +
        `_Generated by CastorWorks Financial Intelligence_`

      let sentSuccessfully = false

      // Send via Email
      try {
        await supabase.functions.invoke('send-email-notification', {
          body: {
            to: adminEmail,
            subject: `CRITICAL: Financial Risk Alert - ${info.projectName}`,
            content: message.replace(/\*/g, '')
          }
        })
        sentSuccessfully = true
        console.log(`[Risk Alerts] Email sent for project: ${info.projectName}`)
      } catch (e: any) {
        console.error(`[Risk Alerts] Email failed for ${info.projectName}:`, e.message)
      }

      if (sentSuccessfully) {
        alertedIds.push(...info.risks.map((r: any) => r.id))
      }
    }

    // 4. Mark as alerted
    if (alertedIds.length > 0) {
      await supabase.from('financial_cashflow_snapshots').update({ is_alerted: true }).in('id', alertedIds)
    }

    return new Response(JSON.stringify({ success: true, alerts_processed: projectRisks.size }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (err: any) {
    console.error('[Risk Alerts] Critical Error:', err)
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
